### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by nuhnuh** [DLR-RM/granite#2]
> granite/src/mapper_sim.cpp:586:41: error: too few arguments to function 'std::pair<double, double> granite::alignSVD(const std::vector<long int>&, Eigen::aligned_vector<Eigen::Matrix<double, 3, 1> >&, const std::vector<long int>&, Eigen::aligned_vector<Eigen::Matrix<double, 3, 1> >&, Sophus::SE3d&, Sophus::Sim3d&, bool)'

**Comment by hobbeshunter** [comment]
Fixed with 6c132f856d5c28cb3888fbbfb39f0d3dda6ff1e3

Note, mapper, mapper_sim and mapper_sim_naive are relics from basalt and are not tested at all, but should compile now.

**Comment by hobbeshunter** [comment]
Thanks for pointing that out.
