### ISSUE TITLE
 error，when cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo 

### ISSUE THREAD

**Issue by SharineLee** [DLR-RM/granite#5]
CMake Error at thirdparty/granite-headers/test/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/sharine/Mine/MyResearch/granite/thirdparty/granite-headers/test/googletest

  does not contain a CMakeLists.txt file.

CMake Error at thirdparty/granite-headers/test/CMakeLists.txt:36 (add_subdirectory):
  The source directory

    /home/sharine/Mine/MyResearch/granite/thirdparty/granite-headers/test/benchmark

  does not contain a CMakeLists.txt file.

**Comment by hobbeshunter** [comment]
Did you clone with `--recurse-submodules`?

If not try `git submodule update --init --recursive`

Does this solve your problem?

**Comment by SharineLee** [comment]
tkank you！i will try.
