### ISSUE TITLE
how can i use grantie vo (without odometry) by ROS?

### ISSUE THREAD

**Issue by SharineLee** [DLR-RM/granite#6]

**Comment by hobbeshunter** [comment]
Hi Sharine,

you have to write a small wrapper around granite. Granite compiles into a library so link against that one. Then you just have to push the images from the ROS subscriber into the optical flow input queue. 

Depending on your setup you may want to use [message synchronizer](http://wiki.ros.org/message_filters) to sync the incoming images from all your cams. 

Cheers
Martin

**Comment by hobbeshunter** [comment]
Have a look at https://github.com/DLR-RM/granite/blob/master/src/vio.cpp#L194 and following. There you see how to setup the system.
