### ISSUE TITLE
Calibration on monocular camera

### ISSUE THREAD

**Issue by alwynmathew** [DLR-RM/granite#8]
I ran monocular camera calibration with 700+ images with April tags on `basalt` and `granite` but got (bit) worse reprojection error. I expected an improved calibration with `granite` when compared to `basalt`. Camera model `ds`, reprojection error in basalt is `0.254697` and granite is `0.254957`. 

As our target application requires accurate measurement at around 20cm from the camera, we used a custom target which is a scaled-down A0 kalibr april-tag target to A3.

Original A0 kalibr april-tag config:
```
"tagCols": 6,
"tagRows": 6,
"tagSize": 0.088,
"tagSpacing": 0.3
```
Our custom A3 kalibr april-tag config:
```
"tagCols": 6,
"tagRows": 6,
"tagSize": 0.03,
"tagSpacing": 0.3
```

**Comment by hobbeshunter** [comment]
Interesting. Camera calibration should be identical to basalt.

Maybe basalt improved a little bit since the fork.
